name: ci

on:
  push:
    branches:
      - main
    paths-ignore:
      - "*/**.md"
      - "*/**.txt"
  pull_request:
    paths-ignore:
      - "*/**.md"
      - "*/**.txt"
  workflow_dispatch:

env:
  CI: true
  NODE_LATEST: 24.x

defaults:
  run:
    shell: bash

jobs:
  check:
    name: check
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 18.x
          - 24.x
        platform:
          - ubuntu-latest

    runs-on: ${{matrix.platform}}

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 2
      - uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{matrix.node-version}}@${{matrix.platform}}-build-${{hashFiles('package-lock.json')}}
          restore-keys: |
            ${{matrix.node-version}}@${{matrix.platform}}-build-
      # - name: dump some variables
      #   run: |
      #     echo '## github object' >> $GITHUB_STEP_SUMMARY
      #     echo '```json' >> $GITHUB_STEP_SUMMARY
      #     echo '${{toJSON(github)}}' >> $GITHUB_STEP_SUMMARY
      #     echo '```' >> $GITHUB_STEP_SUMMARY
      - uses: actions/setup-node@v5
        with:
          node-version: ${{matrix.node-version}}
      - name: remove .npmrc on node 18 so npm install works
        if: matrix.node-version == '18.x'
        run: |
          rm -f .npmrc
          npm config set package-lock=true
          npm config set save-exact=true
      - run: npm install
      - run: npm run depcruise
        if: matrix.node-version == env.NODE_LATEST
      - run: npm run lint
        if: matrix.node-version == env.NODE_LATEST
      - run: npm run test:cover
        if: matrix.node-version == env.NODE_LATEST
      - run: npx tsx --test src/*.spec.ts src/**/*.spec.ts
        if: matrix.node-version == '18.x'
      - run: npm run build
      - name: emit coverage results to step summary
        if: always() && matrix.node-version == env.NODE_LATEST
        run: |
          echo '## Code coverage' >> $GITHUB_STEP_SUMMARY
          npx tsx  tools/istanbul-json-summary-to-markdown.ts < coverage/coverage-summary.json >> $GITHUB_STEP_SUMMARY
      - name: emit full depcruise results to step summary
        if: always() && matrix.node-version == env.NODE_LATEST
        run: |
          yarn --silent depcruise --output-type markdown >> $GITHUB_STEP_SUMMARY
      - name: on pushes to the default branch emit graph to the step summary
        if: always() && matrix.node-version == env.NODE_LATEST && github.event_name == 'push' && github.ref_name == github.event.repository.default_branch
        run: |
          echo '## Visual overview' >> $GITHUB_STEP_SUMMARY
          echo '```mermaid' >> $GITHUB_STEP_SUMMARY
          yarn --silent depcruise:graph:diff:mermaid >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
      - name: on pull requests emit depcruise graph to step summary with changed modules highlighted
        if: always() && matrix.node-version == env.NODE_LATEST && github.event_name == 'pull_request' && github.ref_name != github.event.repository.default_branch
        run: |
          echo '## Visual diff' >> $GITHUB_STEP_SUMMARY
          echo Modules changed in this PR have a fluorescent green color. >> $GITHUB_STEP_SUMMARY
          echo '```mermaid' >> $GITHUB_STEP_SUMMARY
          SHA=${{github.event.pull_request.base.sha}} yarn --silent depcruise:graph:diff:mermaid >> $GITHUB_STEP_SUMMARY
          echo '' >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY

  check-windows:
    env:
      PLATFORM: windows-latest
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{env.NODE_LATEST}}@${{env.PLATFORM}}-build-${{hashFiles('package-lock.json')}}
          restore-keys: |
            ${{env.NODE_LATEST}}@${{env.PLATFORM}}-build-
      - uses: actions/setup-node@v5
        with:
          node-version: ${{env.NODE_LATEST}}
      - name: install & build
        run: |
          npm install
          npm run build
      - run: npm test