name: ci

on:
  push:
    branches:
      - main
    paths-ignore:
      - "*/**.md"
      - "*/**.txt"
  pull_request:
    paths-ignore:
      - "*/**.md"
      - "*/**.txt"
  workflow_dispatch:

env:
  CI: true
  NODE_LATEST: 18.x

defaults:
  run:
    shell: bash

jobs:
  check:
    name: check
    strategy:
      fail-fast: true
      matrix:
        node-version:
          - 12.x
          - 18.x
        platform:
          - ubuntu-latest

    runs-on: ${{matrix.platform}}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{matrix.node-version}}@${{matrix.platform}}-build-${{hashFiles('package.json')}}
          restore-keys: |
            ${{matrix.node-version}}@${{matrix.platform}}-build-
      # - name: dump some variables
      #   run: |
      #     echo '## github object' >> $GITHUB_STEP_SUMMARY
      #     echo '```json' >> $GITHUB_STEP_SUMMARY
      #     echo '${{toJSON(github)}}' >> $GITHUB_STEP_SUMMARY
      #     echo '```' >> $GITHUB_STEP_SUMMARY
      - uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}
      - run: npm install
      - run: npm run depcruise
      - name: lint on platforms other than 12.x
        if: matrix.node-version != '12.x'
        run: npm run lint
      - run: npm run test:cover
      - run: npm run build
      - name: emit coverage results to step summary
        if: always() && matrix.node-version == env.NODE_LATEST
        run: |
          echo '## Code coverage' >> $GITHUB_STEP_SUMMARY
          node tools/istanbul-json-summary-to-markdown.mjs < coverage/coverage-summary.json >> $GITHUB_STEP_SUMMARY
      - name: on pushes to the default branch emit full depcruise results to step summary
        if: always() && matrix.node-version == env.NODE_LATEST && github.event_name == 'push' && github.ref_name == github.event.repository.default_branch
        run: |
          yarn --silent depcruise --output-type markdown >> $GITHUB_STEP_SUMMARY
          echo '## Visual overview' >> $GITHUB_STEP_SUMMARY
          echo '```mermaid' >> $GITHUB_STEP_SUMMARY
          yarn --silent depcruise --exclude ".spec.mjs$" --include-only "^(src)" --output-type mermaid >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
      - name: on pull requests emit depcruise results + diff graph to step summary
        if: always() && matrix.node-version == env.NODE_LATEST && github.event_name == 'pull_request' && github.ref_name != github.event.repository.default_branch
        run: |
          yarn --silent depcruise --output-type markdown >> $GITHUB_STEP_SUMMARY
          echo '## Visual diff' >> $GITHUB_STEP_SUMMARY
          echo '```mermaid' >> $GITHUB_STEP_SUMMARY
          SHA=${{github.event.pull_request.base.sha}} yarn --silent depcruise:graph:diff:mermaid >> $GITHUB_STEP_SUMMARY
          echo '' >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY

